---
- hosts: all
  become: yes
  become_user: root

  tasks:
    #Upgrade PHP
    - name: PHP Package Installation
      shell: sudo apt-get install software-properties-common -y

    - name: PHP repository from Ondřej
      shell: sudo add-apt-repository ppa:ondrej/php -y

    - name: Updates
      shell: sudo apt-get update -y

    - name: Install PHP 8.1
      shell: sudo apt-get install php8.1 -y

    - name: Install PHP 8.1 Extention
      shell: sudo apt-get install libapache2-mod-php8.1 php8.1-fpm libapache2-mod-fcgid php8.1-curl php8.1-dev php8.1-gd php8.1-mbstring php8.1-zip php8.1-mysql php8.1-xml -y




